### ISSUE TITLE
allow defining Dockerfile src in a plan

### ISSUE THREAD

**Issue by leonjza** [sensepost/dwn#1]
eg.

```yaml
name: foo
image_source: |
 FROM alpine
 RUN apk add something
 COMMAND bash
ports:
 - 4444:4444
```
